[project]
name = "rpvmmgurobimodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gurobipy>=12.0.1",
    "pandas>=2.2.3",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
